"""Saving a photo against one log entry - a completed repair, mostly.

A landlord's own proof a job was actually done, or what a vendor left behind. Kept
deliberately small: one photo per entry, re-encoded to a fixed size and format regardless
of what arrived, and stripped of EXIF on the way - a phone photo's metadata routinely
carries the GPS coordinates of where it was taken, which is not something to keep next to
a tenant's address without anyone having decided to.
"""

from __future__ import annotations

import io
import re
import uuid
from pathlib import Path

MAX_UPLOAD_BYTES = 15_000_000
MAX_DIMENSION = 1600
JPEG_QUALITY = 82

_UNSAFE = re.compile(r"[^A-Za-z0-9_-]")


class PhotoError(ValueError):
    """The upload cannot be saved, with a reason worth showing."""


def _safe_segment(text: str) -> str:
    """An owner or entry id, made safe to use as a path segment - never trust an id that
    arrived over the wire to already be one, even though these are only ever generated by
    this app itself."""
    return _UNSAFE.sub("_", text)[:128] or "x"


def save_photo(data_dir: Path, owner_id: str, entry_id: str, raw: bytes) -> str:
    """Re-encode and save one photo. Returns the relative path to store on the entry.

    Raises ``PhotoError`` for anything too big or not really an image - Pillow opening it
    is the actual check; a file extension or a claimed content-type is only ever what the
    sender says it is, never proof.
    """
    from PIL import Image, UnidentifiedImageError

    if not raw:
        raise PhotoError("No file arrived.")
    if len(raw) > MAX_UPLOAD_BYTES:
        raise PhotoError(f"That photo is over the {MAX_UPLOAD_BYTES // 1_000_000}MB limit.")
    try:
        image = Image.open(io.BytesIO(raw))
        image.verify()
        # verify() leaves the image unusable for further work, per Pillow's own docs -
        # reopen it once confirmed genuine.
        image = Image.open(io.BytesIO(raw))
        image.load()
    except (UnidentifiedImageError, OSError) as exc:
        raise PhotoError("That doesn't look like a photo Mark can read.") from exc
    if image.mode not in ("RGB", "L"):
        image = image.convert("RGB")
    image.thumbnail((MAX_DIMENSION, MAX_DIMENSION))

    folder = data_dir / "attachments" / _safe_segment(owner_id)
    folder.mkdir(parents=True, exist_ok=True)
    filename = f"{_safe_segment(entry_id)}-{uuid.uuid4().hex[:8]}.jpg"
    destination = folder / filename
    image.save(destination, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    return f"{_safe_segment(owner_id)}/{filename}"


def photo_file(data_dir: Path, photo_path: str) -> Path | None:
    """Resolve a stored ``photo_path`` back to a real file, or ``None`` if it has gone
    missing or the value doesn't resolve to somewhere under the attachments folder - the
    row is only ever written by ``save_photo`` above, but a path is read back off disk
    trusting nothing, the same discipline the rest of this module already holds itself to.
    """
    if not photo_path or "/" not in photo_path:
        return None
    root = (data_dir / "attachments").resolve()
    resolved = (root / photo_path).resolve()
    if root not in resolved.parents:
        return None
    return resolved if resolved.is_file() else None


def delete_photo(data_dir: Path, photo_path: str) -> None:
    path = photo_file(data_dir, photo_path)
    if path is not None:
        path.unlink(missing_ok=True)
